# Generated by Django 5.0.1 on 2024-01-19 04:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('toppings', models.CharField(max_length=30)),
                ('size', models.CharField(choices=[('small', 'small'), ('medium', 'medium'), ('large', ' large')], default='---', max_length=10)),
                ('price', models.CharField(choices=[('10', '$10'), ('20', '$20'), ('30', '$30')], default='---', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('restaurant_name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=256)),
                ('city', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='RestPizza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(choices=[('10', '$10'), ('20', '$20'), ('30', '$30')], default='---', max_length=2)),
                ('pizza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizza.pizza')),
                ('rest_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizza.restaurant')),
            ],
        ),
    ]
