# Generated by Django 5.0.1 on 2024-01-19 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0005_alter_restaurant_pizza'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='pizza',
        ),
    ]
