# Generated by Django 5.0.1 on 2024-01-19 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0008_alter_pizza_size_alter_restaurant_pizza_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='pizza',
        ),
    ]
