# Generated by Django 5.0.1 on 2024-01-19 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0009_remove_restaurant_pizza'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='pizza',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='pizza.pizza'),
        ),
    ]
